- NumPy

N-Dimentional Array

컬러 이미지는 3차원 여러장은 4차원(1000장)

흑백 이미지도 3차원

차원, 데이터 타입 항상 확인하면서 학습

넘파이 연산을 할 때 어느 축을 기준으로 계산을 할지 정할 수 있음

넘파이 어레이에는 파이썬 리스트와 다르게 같은 타입이 들어가야 함

##파이썬 리스트와 넘파이 속도 비교

In [ ]:
import numpy as np

In [ ]:
python_list = [i for i in range(1000000)]

In [ ]:
arr = np.array(python_list)

In [ ]:
# 매직 커멘드
%%timeit
sum(python_list)

7.97 ms ± 1.83 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [ ]:
%%timeit
np.sum(arr)

334 µs ± 16.1 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


## 넘파이 배열 생성과 기본 속성

In [ ]:
arr1 = np.array([1,2,3])

type(arr1)
print(arr1)
arr1 # 이렇게 프린트하면 타입까지 알 수 있음

[1 2 3]


array([1, 2, 3])

In [ ]:
arr1.shape

(3,)

In [ ]:
a = (2,) # 튜플
a = () # 튜플
a = (2) #int 타입
type(a)

int

In [ ]:
# 리스트는 원소 바꿀 수 있음
l = [1,2,3]
l[0] = 3
l

[3, 2, 3]

In [ ]:
# 튜플은 못 바꿈
# 따라서 딥러닝에서는 튜플이 많이 사용됨
t = (1,2,3)
t[0] = 3

TypeError: 'tuple' object does not support item assignment

In [ ]:
# 리스트를 받아드리는 함수는 대부분 튜플도 받아드림
np.array([1,2,3])
np.array((1,2,3))

array([1, 2, 3])

In [ ]:
# 이차원도 가능
arr2 = np.array([[1,2],[3,4],[5,6]])

In [ ]:
# 감차원도 가능
arr3 = np.array([[[1,2],[3,4]],
                  [[5,6], [7,8]],
                 [[4,6], [5,5]]])

arr3.shape

(3, 2, 2)

In [ ]:
arr2.dtype

dtype('int64')

In [ ]:
arr2.ndim

2

In [ ]:
# 내용이 0으로 채워진 배열 만들기
# 딥러닝 때 특정 가중치를 넣어주고 싶을 때도 사용
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## 인덱싱(indexing)과 슬라이싱(slicing)

In [ ]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [ ]:
arr[3]

4

In [ ]:
arr[-1]

5

In [ ]:
arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# 파이썬 문법
arr[0][2]

3

In [ ]:
# 넘파이 문법
arr[0,0]
arr[0,]

array([1, 2, 3])

# 불리언 인덱싱(Boolean indexing)

In [ ]:
arr = np.array([1,2,3,4,5])
b = [False, True, False, True, False]
arr[1:3]
# 가지고 오고 싶은 곳에는 True 아닌 곳에는 False
arr[b]

array([2, 4])

In [ ]:
# 조건에 맞춰서 요소 가져오기
arr > 3

array([False, False, False,  True,  True])

In [ ]:
arr[arr>3]

array([4, 5])

In [ ]:
arr2 = np.array([[1,2,3],
                [4,5,6]])

In [ ]:
# 일차원으로 바꿤요
arr2[arr2>2]

array([3, 4, 5, 6])

In [ ]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# 얘는 끝까지 전부다 프린트
arr[3:]

# 얘는 마지막 앞까지 읽어옴
arr[3:-1]

# 0부터 끝까지
arr[:]

# 6부터 끝까지
arr[-4:]

array([6, 7, 8, 9])

## 배열의 연산

In [ ]:
a = [1,2,3]
b = [3,4,5]

In [ ]:
# 파이썬 리스트는 두개의 리스트를 단순 결합하기만 함
a + b

[1, 2, 3, 3, 4, 5]

In [ ]:
a = np.array([1,2,3])
b = np.array([3,4,5])

In [ ]:
# 넘파이의 어레이는 같은 위치에 있는 요소를 더 함
a + b

array([4, 6, 8])

In [ ]:
# 브로드캐스팅
# 1이 내부적으로 [1,1,1]로 바뀜
a + 1

array([2, 3, 4])

In [ ]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [ ]:
arr.sum(), arr.mean()

(10, 2.5)

In [ ]:
np.sum(arr), np.mean(arr)

(10, 2.5)

In [ ]:
arr2 = np.array([[1,3,2],
                 [2,3,4]])
arr2

array([[1, 3, 2],
       [2, 3, 4]])

In [ ]:
arr2.sum()
arr2.sum(axis=0)
arr2.sum(axis=1)

array([6, 9])

In [ ]:
arr2.mean()
arr2.mean(axis=0)
arr2.mean(axis=1)

array([2., 3.])

In [ ]:
arr2 = np.array([[1,3,2],
                 [2,3,4]])
arr2

array([[1, 3, 2],
       [2, 3, 4]])

In [ ]:
arr2.shape

(2, 3)

In [ ]:
# shape을 다시 바꾸고 싶을 때
arr2.reshape(3,2)
arr2.T

array([[1, 3],
       [2, 2],
       [3, 4]])

In [ ]:
# 삼차원으로 바꾸기
# 하나 짜리가 2개 모여 있는게 3개 있음
arr2.reshape(3,2,1)

array([[[1],
        [3]],

       [[2],
        [2]],

       [[3],
        [4]]])

In [ ]:
# 위는 2차원으로 새로 모양 한 줄, 아래는 1차원으로 가로 모양 한 줄
arr2 = [[1],[2],[3]]
arr2 = [1,2,3]